test: main.c util/clock.c util/log.c util/util.c ship.c ship_cam.c math/mathutil.c math/vector4f.c math/matrix44f.c config.h
	gcc -g -o test main.c util/clock.c util/log.c util/util.c ship.c ship_cam.c math/mathutil.c math/vector4f.c math/matrix44f.c -lSDL2 -lGLU -lGLX_mesa -lm
